{% set version = "0.16.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgexf
  version: {{ version|replace("-", "_") }}

source:
  fn: rgexf_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rgexf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rgexf/rgexf_{{ version }}.tar.gz
  sha256: 2a671df9ac70cfefd4092754317cb28e32a33df345b80e1975bf838e838245ee

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip    # [win]
  host:
    - r-base
    - r-servr
    - r-xml
    - r-igraph
  run:
    - r-base
    - r-servr
    - r-xml
    - r-igraph

test:
  commands:
    - $R -e "library('rgexf')"           # [not win]
    - "\"%R%\" -e \"library('rgexf')\""  # [win]

about:
  home: https://gvegayon.github.io/rgexf
  license: MIT
  summary: Create, read and write 'GEXF' (Graph Exchange 'XML' Format) graph files (used in 'Gephi'
    and others). Using the 'XML' package, it allows the user to easily build/read graph
    files including attributes, 'GEXF' visual attributes (such as color, size, and position),
    network dynamics (for both edges and nodes) and edge weighting. Users can build/handle
    graphs element-by-element or massively through data-frames, visualize the graph
    on a web browser through 'gexf-js' (a 'javascript' library) and interact with the
    'igraph' package.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
