appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: kuwnHoxLdeBG9rLuSKt4CoJSiW9rHqNPYazHUijZYHvCjcbroJRU3HWhR4ASPkoE+zg7sZvVuA+HeYUiCcwSpFGx6NjSi1ujoWgu0+q7hWWVz44O0pSX+5ovSLc+UiiE0TfIotzj0rzNMBAQ3f3WEspncCYoJzuLmMGYnsVLJnTP71AJexy2xPhpdX2x3CnLaGggiT5pXXyTOFuX3DxTSUVMagiEbFvJqglc/Yas6tnl1s5TgHbCwU+H875TiNns+wEKkfAJ2f2sO47mohTXTKSIxAhM6hK9d/YZaJ2tHuR4/0a667OsGwTGNDNqUvEYz/wfhZwNuX/zg4+vaU4PrW7klov+NcbnjKfHZPeNScZnugRV496WcbqfR1rGepqUfVZbQIJGWDpY6mayPeF9nZ31DV4rO9O6wFOf2cFiU57ILt934Req9UECfQh5+ltraeqgNptpjIqb2PVA2bZW4J4NvUrAdXmJ4h/o0RSSBy3aFbYced6DVs0XmmJgmeXbsDRI3ApcTOLpDPx3ZtdyYXHyqmie+9Zpv1S9xt+VfTfWC/GZrZYeVzzs8f3udrQby99C244wkaPHlMjd6kXWD0TcmOTN4IUAgXeW9cLnyBiGfrImyDuZTOnxCNsfGgQ22iAmEu4iDuvSCUuucvYCEl4++TZSf970F71pvtB+6Mo=
conda_forge_output_validation: false
